name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: '3.10'
        
    - run: pip install cerebrium requests pillow numpy
    - run: docker build -t mtailor .
        
    - name: Deploy
      env:
        INFERENCE_TOKEN: ${{ secrets.INFERENCE_TOKEN }}
      run: |
        cerebrium login --api-key $INFERENCE_TOKEN
        cerebrium deploy
        
    - run: sleep 100
    - run: python test_server.py --preset
    - run: |
        curl -H "Authorization: Bearer ${{ secrets.INFERENCE_TOKEN }}" \
             https://api.cortex.cerebrium.ai/v4/p-eb829d71/mtailor/health 